# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_festival_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalunit',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival_units', to='festival.Festival'),
        ),
    ]
