# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_festivalunit_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='poster_link',
            field=models.CharField(default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='festivalunit',
            name='end_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='festivalunit',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
