# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_auto_20170422_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(default='2017 축제', max_length=250),
        ),
    ]
