# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0008_auto_20170423_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalunit',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='festivalunit',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
