# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='imagelink',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='naverlink',
            new_name='naver_link',
        ),
    ]
