# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20170422_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='university',
            name='naver_link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
